# Generated by Django 3.0 on 2020-04-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_recipe_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(default='Default Meal Plan', max_length=100),
            preserve_default=False,
        ),
    ]
